### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by refty10** [ygkn/storybook-opener#7]
<img src='https://i.gyazo.com/79d06dce195cc365850fee905a3a24e3.png'>

.storiesのあるディレクトリのtsxファイルを開いてもアイコンが表示されない。

確認したエラー
```
[Extension Host] TypeError: Cannot destructure property 'packageJson' of '(intermediate value)' as it is undefined.
    at loadPresets (c:\Users\refty\.vscode\extensions\ygkn.storybook-opener-1.1.9\out\loadPresets.js:8:13)
    at loadStoryUrlGetter (c:\Users\refty\.vscode\extensions\ygkn.storybook-opener-1.1.9\out\getGetStoryUrl.js:16:21)
    at c:\Users\refty\.vscode\extensions\ygkn.storybook-opener-1.1.9\out\extension.js:71:45
    at getOrFallbackFromWorkspaceCache (c:\Users\refty\.vscode\extensions\ygkn.storybook-opener-1.1.9\out\extension.js:40:28)
    at reload (c:\Users\refty\.vscode\extensions\ygkn.storybook-opener-1.1.9\out\extension.js:60:34)
```

**Comment by ygkn** [comment]
thanks for reporting issue!

this bug will be fixed in v1.1.10
